# SPDX-FileCopyrightText: 2026 Jens Koehler <kwin-effect-upscale@koehler-speyer.de>
# SPDX-License-Identifier: GPL-2.0-or-later
# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: en-US
enable_free_tier: true
reviews:
  request_changes_workflow: true
  fail_commit_status: true
  high_level_summary: false
  poem: false
  auto_review:
    enabled: true
    auto_incremental_review: true
    auto_pause_after_reviewed_commits: 0
    drafts: true
  pre_merge_checks:
    docstrings:
      mode: "off"
  finishing_touches:
    docstrings:
      enabled: false
    unit_tests:
      enabled: false
    autofix:
      enabled: false
    fix_ci:
      enabled: false
    resolve_merge_conflict:
      enabled: false
